### ISSUE TITLE
Kinetic chamber resets items when right clicked

### ISSUE THREAD

**Issue by CubicBerserker** [wildcardgamez/Buddycards-Core#11]
Using version 1.18.2-3.2.0

Adding an item to a kinetic chamber and then removing it again resets the item to some default state. Tools have enchantments removed and durability restored, potions turn into uncraftable potions, etc.

**Comment by wildcardgamez** [comment]
Ah, didnt think about that edge case, ill fix it for the next version

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/Buddycards-Core/commit/4f57c507049010b5bd9f380dae0dd46e39cdc462
Fixed for next update
