### ISSUE TITLE
Medals no longer curios in new update

### ISSUE THREAD

**Issue by BarryHarton** [wildcardgamez/Buddycards-Core#12]
I've just updated buddycards 1.18.2, and the medals no longer fit in the medal slot. They no longer have a slot type tooltip either.

**Comment by wildcardgamez** [comment]
Might be an issue of missing tag, easy fix Ill work on tomorrow

**Comment by CubicBerserker** [comment]
The medals work fine for me. Tooltip and everything. Did you empower it?

**Comment by wildcardgamez** [comment]
Yeah I'm going to have to close this on the fact that it isn't an issue in the latest version. I don't know what you did, but yeah it's possible you are using a blank medal (which is unusable without empowering it)

**Comment by BarryHarton** [comment]
Found a fix, turns out it's an issue with the old 3rd party expansions (colonycards, customcards). I just removed these from the openloader folder in config and that did it
