### ISSUE TITLE
Baby zombie piglins drop base packs instead of nether packs

### ISSUE THREAD

**Issue by CubicBerserker** [wildcardgamez/Buddycards-Core#16]

**Comment by wildcardgamez** [comment]
Not an issue, baby zombie piglins have a chance to drop base because they are zombies and nether because they are piglins

**Comment by CubicBerserker** [comment]
Really? The config only refers to the chance of dropping nether packs and I can only get them to drop base pack even thought I've set the drop chance to the maximum value.

**Comment by wildcardgamez** [comment]
I believe it refers to baby zombies and baby piglins, though I may be
mistaken. I'll double check tomorrow just in case
