### ISSUE TITLE
Tool Rendering Issue

### ISSUE THREAD

**Issue by wildcardgamez** [wildcardgamez/Buddycards-Core#18]
This is just being put here so nobody reports it. The item models for tools are messed up. Will be fixed soon

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/208481266-9e1cb885-c278-4da5-8838-3ba735654eab.png)
Do you mean this kind of problem?

**Comment by wildcardgamez** [comment]
Yep.

**Comment by wildcardgamez** [comment]
It's an easy fix but the current build is half finished with battles

**Comment by Dr-WeiAL** [comment]
Great, I look forward to the release

**Comment by wildcardgamez** [comment]
Fixed in newest release
