### ISSUE TITLE
Missing card in collection while having them all ...

### ISSUE THREAD

**Issue by tomagreg** [wildcardgamez/Buddycards-Core#23]
Hello, 

I have collected all base set cards ( stars ans normals), my binder is full but i didn't got the medal, in the success page i see 26/27. 

I tried removing them all from my inventory and replacing them afterward but still missing one.
Do you have an idea of what could have happend ?

Thanks
(English is not my first language sorry about it)

**Comment by wildcardgamez** [comment]
Sorry for the late response, but this github is for 1.18 onwards. 1.18 has 36 cards in the base set and doesn't have these issues anymore thanks to a new system in place. 1.16 and 1.17 are no longer being supported.
