### ISSUE TITLE
It would be cool to be able to grade the Booster Packs

### ISSUE THREAD

**Issue by N0VVAH** [wildcardgamez/Buddycards-Core#24]
A player on my server asked about if you could grade packs and I also thought it would be funny if you grade the packs in the same way in which you grade cards.

**Comment by wildcardgamez** [comment]
Could be interesting, but I am unsure if there would be enough interest to justify the changes and additions that would have to be done. The grading system itself is relatively unpopular as it is, so I think I'm going to just say it won't be added. Thank you for the suggestion though.
