### ISSUE TITLE
Card display indestructible

### ISSUE THREAD

**Issue by PanameSG** [wildcardgamez/Buddycards-Core#7]
Hi, I've a little issue but annoying, the oak cards display can't be remove from my wall, I tried with other color, same result [https://youtu.be/ZhGWEjW8V70](url)

**Comment by wildcardgamez** [comment]
I'm surprised it took this long for it to get caught if this is what I think it is, looking into it now.

**Comment by wildcardgamez** [comment]
Doesn't seem to be an issue in the latest version, it'd be easier if you shared your version, but I don't really know when this was fixed. If you update to one of the more recent versions you should be good to go :D
