### ISSUE TITLE
Weird crash when placing down Card Displays

### ISSUE THREAD

**Issue by Asveste** [wildcardgamez/Buddycards-Core#8]
The title basically says everything.
I just want to know if this is caused by RoadRunner because it's mentioned at the very beginning of the crash log.
If it is RoadRunners fault then sorry for bothering you 😅 

Edit: This is in 1.16.5

Crash Log:
[crash-2022-07-24_05.26.36-client.txt](https://github.com/wildcardgamez/Buddycards-Core/files/9175150/crash-2022-07-24_05.26.36-client.txt)

**Comment by wildcardgamez** [comment]
1.16.5 is dropped, this is the buddycards core github, the buddycards github is archived. This is an odd issue, but looks like you somehow got multiple tile entities jammed into one block. Good luck

**Comment by Asveste** [comment]
Oh okay, well yeah I just wanted to ask nicely if you've got any idea whats happening so thank you
