### ISSUE TITLE
Golden grading sleeves and booster boxes aren't stackable

### ISSUE THREAD

**Issue by CubicBerserker** [wildcardgamez/Buddycards-Core#9]
Using version 1.18.2-3.2.0

Golden grading sleeves only stack up to 1, unlike other types of grading sleeve.

The same is the case for booster boxes, with the exception of mystery set booster box, which stacks to 64.

**Comment by wildcardgamez** [comment]
Will look into it, I think I know why it does this though, should be an easy fix

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/Buddycards-Core/commit/a825532ae56661fcda221adf7fa20e132c42d43d
Fixed for next update
